### ISSUE TITLE
Inconsistent results on PASCAL-S

### ISSUE THREAD

**Issue by KingJamesSong** [weijun88/LDF#4]
Hi,
  I just found your provided saliency maps do not have the same evaluation results on PASCAL-S dataset as reported in the paper. I binarize the PASCAL-S dataset for evaluation.
  Did you process the PASCAL-S dataset differently?

**Comment by weijun-arc** [comment]
Do you write your own evaluation codes? There may exist many small differences between your codes with the existing evaluation codes. So please use the codes in the `eval` folder to evaluate your saliency maps.

**Comment by KingJamesSong** [comment]
No, I do use your evaluation codes, but there are still some differences. For example, the MAE is 0.062 instead of 0.060.

**Comment by weijun-arc** [comment]
I have try to eval the saliency maps again, here is the results, which is exactly the reported scores. I think the difference may come from the environment, for example, the version of MATLAB
<img width="356" alt="屏幕截图 2020-10-27 134643" src="https://user-images.githubusercontent.com/13310328/97261955-df745b00-185a-11eb-8138-ad6fec2a3e52.png">

**Comment by KingJamesSong** [comment]
Which version are you using? I am using MATLABL2018b.

**Comment by weijun-arc** [comment]
We use the MATLAB R2018a on CentOS Linux release 7.6.1810 
<img width="841" alt="屏幕截图 2020-10-27 162307" src="https://user-images.githubusercontent.com/13310328/97275318-c4144a80-1870-11eb-9291-220c69de44cb.png">
